#SPDX-License-Identifier: MIT-0
---
# tasks file for tailscale
- name: Include Tailscale tasks
  ansible.builtin.import_tasks: tailscale/main.yml

- name: Include networking tasks
  ansible.builtin.import_tasks: networking/main.yml
